name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "vzr1r1f65ute4mo8buqqs8jq"
name = "Ready"

  [[processes.tasks]]
  id = "qj5m5bbkwjv4bn45l32w4zdg"
  title = "EMC and EMI Improvement"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "iyiyxyx4bhnv03vv91mpk374"
  title = "Finalize the UI board design decision"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "b4dt00e0shxkkk6olwoqukq2"
  title = "Check Socket to be bougth or to be design"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "je6ctrmdgghoz975rbslq7l0"
  title = "Manage the net classes and design rules "
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "bmucv228iqkb5kouwqpfxse2"
  title = "Place the Polygon Pours"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "omgy6vl7ehqh598ss3a70qz6"
  title = "Create Slots between 20A and rest"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"
tasks = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "qlhevbsdgvl9bljje2pqf8xp"
  title = "Check Relay Block For Electrical Calculations"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "fdndp3fowvhddt4pwu7o7x85"
  title = "Check AC Block for Electrical Calculations"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "e4oavvytd2m2sc28cxaon4es"
  title = "Use SS8050 for Relay Driving"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "p17vwkorl0ajn806b73jpdsv"
  title = "Fix MCP23017 input voltage as 3V3"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "wca0ospr94ti4q6vchyc75vr"
  title = "Use Faston Tabs for the production"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "d9jkxwinllcg5ir3u9svvaw0"
  title = "Update MCP23017 Schematic and PCB"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "ziliq9s7fb693p4d9ymfh061"
  title = "Connect MCP23017 Interrupt pins to ESP32"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "x4xf6t1vricxw7m5fsxj4skm"
  title = "Update AC-DC power converter from HLK-5M05 to HLK-10M05"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "oa14v3fvcwou9ilobju80nz6"
  title = "Find an ESP32 which fits to the project "
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
