name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"
tasks = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "ziliq9s7fb693p4d9ymfh061"
  title = "Connect MCP23017 Interrupt pins to ESP32"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"

  [[processes.tasks]]
  id = "x4xf6t1vricxw7m5fsxj4skm"
  title = "Update AC-DC power converter from HLK-5M05 to HLK-10M05"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "qlhevbsdgvl9bljje2pqf8xp"
  title = "Check Relay Block For Electrical Calculations"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "fdndp3fowvhddt4pwu7o7x85"
  title = "Check AC Block for Electrical Calculations"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "e4oavvytd2m2sc28cxaon4es"
  title = "Use SS8050 for Relay Driving"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "p17vwkorl0ajn806b73jpdsv"
  title = "Fix MCP23017 input voltage as 3V3"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "wca0ospr94ti4q6vchyc75vr"
  title = "Use Faston Tabs for the production"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "d9jkxwinllcg5ir3u9svvaw0"
  title = "Update MCP23017 Schematic and PCB"
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]
